
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"   # Localhost:3000 -> Next.js
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"   # Localhost:8000 -> FastAPI
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
